### PR TITLE
HAAR-998: correct base url on ExternalUserController

### PR DESCRIPTION
**Pull request by AlTurner-MOJ**

### CODE REVIEW

**Review by karenmillermoj — APPROVED** [review]
lgtm - wondering if we should move this to just "UserController" ? not sure

**Comment by AlTurner-MOJ** [comment]
> 

Agree @karenmillermoj - have updated that too

**Review by karenmillermoj — DISMISSED** [review]
lgtm

**Review by karenmillermoj — APPROVED** [review]
lgtm

**Pull request merged**
